import { CircleStop, Cloud, File, FileText, Globe2, LoaderCircle, Monitor, Paperclip, Terminal, ThumbsDown, ThumbsUp, X } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import type { ActivityEvent, Agent, Attachment, ConnectionState, Message, ReactionKind } from "@/domain/types";

const activityIcon = { browser: Globe2, terminal: Terminal, file: FileText, handoff: Cloud, status: Cloud };
function textOf(message: Message) { return message.parts.filter((part) => part.type === "text").map((part) => part.text).join(""); }
const formatBytes = (bytes: number) => bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(bytes < 10 * 1024 ? 1 : 0)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
function SubmitArrowIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m5 12 7-7 7 7" /><path d="M12 19V5" /></svg>; }
export function MessageView({ message, activities, onReact }: { message: Message; activities: ActivityEvent[]; onReact(messageId: string, reaction: ReactionKind): Promise<void> }) {
  const relevant = message.parts.flatMap((part) => part.type === "activity" ? activities.filter((activity) => activity.id === part.activityId) : []);
  const attachments = message.parts.flatMap((part) => part.type === "attachment" ? [part.attachment] : []);
  return <div className={`message ${message.role}`}>
    {textOf(message) && <div className="message-body">{textOf(message)}{message.streaming && <span className="streaming-caret" />}</div>}
    {attachments.length > 0 && <div className="message-attachments">{attachments.map((attachment) => <div key={attachment.id}><File size={15} /><span><strong>{attachment.name}</strong><small>{formatBytes(attachment.size)} · {attachment.mediaType}</small></span></div>)}</div>}
    {relevant.map((activity) => { const Icon = activityIcon[activity.kind]; return <div className="activity-card" key={activity.id}><div className="activity-summary"><span className={`activity-icon ${activity.status}`}><Icon size={15} /></span><div><strong>{activity.title}</strong><span>{activity.detail}</span></div><span className={`activity-state ${activity.status}`}>{activity.status === "running" ? <LoaderCircle className="spin" size={15} /> : "Done"}</span></div></div>; })}
    {message.role === "agent" && !message.streaming && <div className="message-reactions"><button aria-label="Mark as useful" aria-pressed={message.reactions?.find((reaction) => reaction.kind === "useful")?.selected ?? false} onClick={() => void onReact(message.id, "useful")}><ThumbsUp size={13} /><span>{message.reactions?.find((reaction) => reaction.kind === "useful")?.count || ""}</span></button><button aria-label="Mark as needs work" aria-pressed={message.reactions?.find((reaction) => reaction.kind === "needs_work")?.selected ?? false} onClick={() => void onReact(message.id, "needs_work")}><ThumbsDown size={13} /><span>{message.reactions?.find((reaction) => reaction.kind === "needs_work")?.count || ""}</span></button></div>}
  </div>;
}
export function Conversation({ agent, messages, activities, connection, onSend, onReact, onReconnect, onToggleDetails }: { agent: Agent; messages: Message[]; activities: ActivityEvent[]; connection: ConnectionState; onSend(text: string, attachments?: Attachment[]): Promise<void>; onReact(messageId: string, reaction: ReactionKind): Promise<void>; onReconnect(): void; onToggleDetails(): void }) {
  const [draft, setDraft] = useState(""); const [attachments, setAttachments] = useState<Attachment[]>([]); const [sending, setSending] = useState(false); const [isScrolled, setIsScrolled] = useState(false); const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const element = scrollRef.current; if (element && typeof element.scrollTo === "function") element.scrollTo({ top: element.scrollHeight, behavior: "smooth" }); }, [messages]);
  async function submit(event: FormEvent) { event.preventDefault(); const text = draft.trim(); if ((!text && attachments.length === 0) || sending) return; setDraft(""); setSending(true); try { await onSend(text, attachments); setAttachments([]); } finally { setSending(false); } }
  async function chooseAttachments() { const selected = await window.runtaCrew?.attachments.choose() ?? []; setAttachments((current) => [...current, ...selected.filter((next) => !current.some((item) => item.id === next.id)).map((item) => ({ ...item, source: "local-selection" as const }))].slice(0, 8)); }
  return <main className="conversation">
    <header className={`conversation-header ${isScrolled ? "scrolled" : ""}`}><h1>{agent.name}</h1><div className="header-actions">{connection !== "connected" && <><span className={`connection ${connection}`}>{connection === "connecting" ? "Connecting" : "Connection lost"}</span><button className="secondary-button" onClick={onReconnect}>Reconnect</button></>}<button className="computer-trigger" aria-label="Open agent computer" onClick={onToggleDetails}><Monitor size={18} /></button></div></header>
    <div className="message-scroll" ref={scrollRef} onScroll={(event) => setIsScrolled(event.currentTarget.scrollTop > 0)}>{messages.length === 0 && <div className="conversation-intro"><div className={`avatar avatar-${agent.id} large`}>{agent.avatar}</div><h2>{agent.name}</h2><p>{agent.goal}</p></div>}{messages.map((message) => <MessageView key={message.id} message={message} activities={activities} onReact={onReact} />)}</div>
    <form className="composer" onSubmit={submit}><textarea aria-label={`Message ${agent.name}`} placeholder={`Message ${agent.name}…`} value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit(); } }} />{attachments.length > 0 && <div className="composer-attachments">{attachments.map((attachment) => <div key={attachment.id}><File size={14} /><span>{attachment.name}</span><small>{formatBytes(attachment.size)}</small><button type="button" aria-label={`Remove ${attachment.name}`} onClick={() => setAttachments((current) => current.filter((item) => item.id !== attachment.id))}><X size={13} /></button></div>)}</div>}<div className="composer-bottom"><button type="button" className="attach-button" aria-label="Attach files" onClick={() => void chooseAttachments()}><Paperclip size={15} /></button><button className="submit-button" aria-label="Send message" disabled={(!draft.trim() && attachments.length === 0) || sending}>{sending ? <CircleStop size={17} /> : <SubmitArrowIcon />}</button></div></form>
  </main>;
}
