import { Check, ChevronsRight, Maximize2, Monitor, ShieldAlert } from "lucide-react";
import { useState } from "react";
import type { ApprovalRequest, CloudComputer } from "@/domain/types";

export function DetailPanel({ agentName, computer, approvals, onApproval, onComputerAction, onClose }: { agentName: string; computer?: CloudComputer; approvals: ApprovalRequest[]; onApproval(id: string, decision: "allow" | "deny", note?: string): Promise<void>; onComputerAction(action: "open" | "takeover"): Promise<{ url: string; mode: "remote" }>; onClose(): void }) {
  const [note, setNote] = useState(""); const [computerBusy, setComputerBusy] = useState(false); const pending = approvals.filter((approval) => approval.status === "pending");
  async function launchComputer(action: "open" | "takeover") { setComputerBusy(true); try { const result = await onComputerAction(action); await window.runtaCrew?.openExternal(result.url); } catch { /* controller exposes the failure through the app error state */ } finally { setComputerBusy(false); } }
  return <aside className="detail-panel"><header><button className="icon-button" aria-label="Close details" onClick={onClose}><ChevronsRight size={18} /></button></header>
    {pending.map((approval) => <section className="approval-card" key={approval.id}><div className="eyebrow warning"><ShieldAlert size={14} /> Approval required</div><h3>{approval.title}</h3><p>{approval.description}</p><div className="scope"><span>This allows:</span>{approval.scope.map((item) => <div key={item}><Check size={13} />{item}</div>)}</div><textarea aria-label="Approval note" placeholder="Add a note (optional)" value={note} onChange={(event) => setNote(event.target.value)} /><div className="approval-actions"><button className="secondary-button danger-text" onClick={() => void onApproval(approval.id, "deny", note)}>Deny</button><button className="primary-button" onClick={() => void onApproval(approval.id, "allow", note)}>Allow once</button></div></section>)}
    <section className="screen-section"><button className="screen-trigger" disabled={computerBusy || computer?.status !== "online"} aria-label={`Open ${agentName}'s screen`} onClick={() => void launchComputer("open")}><span className="computer-preview">{computer?.previewUrl ? <img src={computer.previewUrl} alt="" /> : <Monitor size={28} />}<span className="screen-hover-action"><Maximize2 size={14} /> Open</span></span><span className="screen-caption">{agentName}'s screen</span></button></section>
  </aside>;
}
