import { Check, ExternalLink, MonitorUp, ShieldAlert, X } from "lucide-react";
import { useState } from "react";
import type { ApprovalRequest, CloudComputer } from "@/domain/types";

export function DetailPanel({ computer, approvals, onApproval, onComputerAction, onClose }: { computer?: CloudComputer; approvals: ApprovalRequest[]; onApproval(id: string, decision: "allow" | "deny", note?: string): Promise<void>; onComputerAction(action: "open" | "takeover"): Promise<{ url?: string; mode: "mock" | "remote" }>; onClose(): void }) {
  const [note, setNote] = useState(""); const [computerAction, setComputerAction] = useState<"open" | "takeover">(); const [computerBusy, setComputerBusy] = useState(false); const pending = approvals.filter((approval) => approval.status === "pending");
  async function launchComputer(action: "open" | "takeover") { setComputerBusy(true); try { const result = await onComputerAction(action); if (result.mode === "remote" && result.url) await window.runtaCrew?.openExternal(result.url); else setComputerAction(action); } catch { /* controller exposes the failure through the app error state */ } finally { setComputerBusy(false); } }
  return <><aside className="detail-panel" data-computer-action={computerAction}><header><button className="icon-button" aria-label="Close details" onClick={onClose}><X size={17} /></button></header>
    {pending.map((approval) => <section className="approval-card" key={approval.id}><div className="eyebrow warning"><ShieldAlert size={14} /> Approval required</div><h3>{approval.title}</h3><p>{approval.description}</p><div className="scope"><span>This allows:</span>{approval.scope.map((item) => <div key={item}><Check size={13} />{item}</div>)}</div><textarea aria-label="Approval note" placeholder="Add a note (optional)" value={note} onChange={(event) => setNote(event.target.value)} /><div className="approval-actions"><button className="secondary-button danger-text" onClick={() => void onApproval(approval.id, "deny", note)}>Deny</button><button className="primary-button" onClick={() => void onApproval(approval.id, "allow", note)}>Allow once</button></div></section>)}
    <section><div className="section-title"><span>Cloud computer</span><span className={`computer-status ${computer?.status}`}>{computer?.status ?? "unknown"}</span></div><div className="computer-preview"><div className="mock-browser"><div className="mock-toolbar"><i /><i /><i /><span>agent.runta.local</span></div><div className="mock-content"><div className="mock-nav"/><div className="mock-page"><span/><strong>{computer?.activeApp ?? "Workspace"}</strong><div/><div/><div className="mock-wide"/></div></div></div><span className="mock-label">Safe mock preview</span></div><dl className="facts"><div><dt>Runtime</dt><dd>{computer?.runtimeName ?? "—"}</dd></div><div><dt>Active app</dt><dd>{computer?.activeApp ?? "None"}</dd></div></dl><div className="computer-actions"><button className="secondary-button" disabled={computerBusy} onClick={() => void launchComputer("open")}><ExternalLink size={15} /> Open</button><button className="primary-button" disabled={computerBusy} onClick={() => void launchComputer("takeover")}><MonitorUp size={15} /> Take over</button></div></section>
  </aside>{computerAction && <div className="computer-overlay"><div className="computer-window"><header><div><span className="status-dot" /> Mock cloud computer</div><button onClick={() => setComputerAction(undefined)}>Close</button></header><div className="computer-placeholder"><MonitorUp size={42} /><h2>{computerAction === "takeover" ? "Takeover preview" : "Computer preview"}</h2><p>This is a safe local mock. No remote desktop session is connected yet.</p><span>Future adapter: Runta Runtime ingress · WebRTC · VNC</span></div></div></div>}</>;
}
