import { Check, ChevronsRight, Loader2, Maximize2, ShieldAlert } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { ApprovalRequest, CloudComputer, CloudComputerSession } from "@/domain/types";
import { VncDesktop, VncSurface } from "./VncDesktop";

export function DetailPanel({ open, width, onResize, agentName, computer, approvals, onApproval, onComputerAction, onClose }: { open: boolean; width: number; onResize(width: number): void; agentName: string; computer?: CloudComputer; approvals: ApprovalRequest[]; onApproval(id: string, decision: "allow" | "deny", note?: string): Promise<void>; onComputerAction(action: "open" | "takeover"): Promise<CloudComputerSession>; onClose(): void }) {
  const [note, setNote] = useState(""); const [computerBusy, setComputerBusy] = useState(false); const [previewSessions, setPreviewSessions] = useState<ReadonlyMap<string, CloudComputerSession>>(() => new Map()); const [previewLoadingId, setPreviewLoadingId] = useState(""); const [computerSession, setComputerSession] = useState<CloudComputerSession>(); const [computerModalOpen, setComputerModalOpen] = useState(false); const [computerFailure, setComputerFailure] = useState<string>(); const pending = approvals.filter((approval) => approval.status === "pending");
  const computerActionRef = useRef(onComputerAction);
  useEffect(() => { computerActionRef.current = onComputerAction; }, [onComputerAction]);
  useEffect(() => {
    const computerId = computer?.id;
    if (!open || computerModalOpen || computer?.status !== "online" || !computerId || previewSessions.has(computerId)) return;
    let alive = true;
    setPreviewLoadingId(computerId);
    void computerActionRef.current("open").then((session) => { if (alive) { setPreviewSessions((current) => new Map(current).set(computerId, session)); setPreviewLoadingId(""); } }).catch(() => { if (alive) setPreviewLoadingId(""); });
    return () => { alive = false; };
  }, [computer?.id, computer?.status, computerModalOpen, open, previewSessions]);
  async function refreshPreview(computerId: string) { setPreviewSessions((current) => { const next = new Map(current); next.delete(computerId); return next; }); setPreviewLoadingId(computerId); try { const session = await computerActionRef.current("open"); setPreviewSessions((current) => new Map(current).set(computerId, session)); } catch { /* controller owns the user-visible error */ } finally { setPreviewLoadingId(""); } }
  async function launchComputer(action: "open" | "takeover") { setComputerModalOpen(true); setComputerSession(undefined); setComputerFailure(undefined); setComputerBusy(true); try { setComputerSession(await onComputerAction(action)); } catch (reason) { setComputerFailure(reason instanceof Error ? reason.message : "Could not connect to the cloud computer."); } finally { setComputerBusy(false); } }
  function closeComputer() { setComputerModalOpen(false); setComputerSession(undefined); setComputerFailure(undefined); }
  const resize = (clientX: number) => onResize(Math.max(280, Math.min(560, window.innerWidth - clientX)));
  return <aside className={`detail-panel ${open ? "is-open" : "is-closing"}`}><div className="detail-resize-handle" role="separator" aria-label="Resize details panel" aria-orientation="vertical" aria-valuemin={280} aria-valuemax={560} aria-valuenow={width} tabIndex={0} onKeyDown={(event) => { if (event.key === "ArrowLeft") { event.preventDefault(); onResize(Math.min(560, width + 16)); } else if (event.key === "ArrowRight") { event.preventDefault(); onResize(Math.max(280, width - 16)); } }} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); resize(event.clientX); }} onPointerMove={(event) => { if (event.currentTarget.hasPointerCapture(event.pointerId)) resize(event.clientX); }} /><header><button className="icon-button" aria-label="Close details" onClick={onClose}><ChevronsRight size={18} /></button></header>
    {pending.map((approval) => <section className="approval-card" key={approval.id}><div className="eyebrow warning"><ShieldAlert size={14} /> Approval required</div><h3>{approval.title}</h3><p>{approval.description}</p><div className="scope"><span>This allows:</span>{approval.scope.map((item) => <div key={item}><Check size={13} />{item}</div>)}</div><textarea aria-label="Approval note" placeholder="Add a note (optional)" value={note} onChange={(event) => setNote(event.target.value)} /><div className="approval-actions"><button className="secondary-button danger-text" onClick={() => void onApproval(approval.id, "deny", note)}>Deny</button><button className="primary-button" onClick={() => void onApproval(approval.id, "allow", note)}>Allow once</button></div></section>)}
    <section className="screen-section"><button className="screen-trigger" disabled={computerBusy || computer?.status !== "online"} aria-label={`Open ${agentName}'s screen`} onClick={() => void launchComputer("open")}><span className="computer-preview">{[...previewSessions].map(([computerId, session]) => <span className={`computer-preview-stream ${computerId === computer?.id ? "is-active" : ""}`} key={computerId}><VncSurface session={session} viewOnly compact onDisconnect={() => void refreshPreview(computerId)} /></span>)}{!previewSessions.has(computer?.id ?? "") && (previewLoadingId === computer?.id ? <span className="computer-preview-loading" role="status" aria-label={`Loading ${agentName}'s screen`}><Loader2 size={18} className="spin" /></span> : <span className="computer-screen-off" aria-hidden="true" />)}<span className="screen-hover-action"><Maximize2 size={14} /> Open</span></span></button><span className="screen-caption">{agentName}'s screen</span></section>
    {computerModalOpen && <VncDesktop session={computerSession} failure={computerFailure} onClose={closeComputer} onReconnect={() => void launchComputer("open")} />}
  </aside>;
}
