import { useEffect, useState, type FormEvent } from "react";
import { X } from "lucide-react";
import type { Agent, CreateAgentInput, UpdateAgentInput } from "@/domain/types";
import type { AppSettings, ThemePreference } from "@/shared/desktop";

function DialogShell({ title, children, onClose }: { title: string; children: React.ReactNode; onClose(): void }) { return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="dialog" role="dialog" aria-modal="true" aria-label={title}><header><div><h2>{title}</h2></div><button className="icon-button" aria-label="Close" onClick={onClose}><X size={18} /></button></header>{children}</section></div>; }
export function CreateAgentDialog({ onClose, onCreate }: { onClose(): void; onCreate(input: CreateAgentInput): Promise<void> }) {
  const [form, setForm] = useState<CreateAgentInput>({ name: "", role: "", goal: "" }); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await onCreate(form); onClose(); } finally { setSaving(false); } }
  return <DialogShell title="Add a cloud agent" onClose={onClose}><p className="dialog-lead">Give your new teammate a clear role and first objective. The mock workspace will be created locally for this preview.</p><form className="dialog-form" onSubmit={submit}><label>Name<input autoFocus required placeholder="e.g. Scout" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Role<input required placeholder="e.g. Customer research lead" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} /></label><label>Initial goal<textarea required placeholder="What should this agent own?" value={form.goal} onChange={(e) => setForm({ ...form, goal: e.target.value })} /></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Creating…" : "Create agent"}</button></div></form></DialogShell>;
}
export function EditAgentDialog({ agent, onClose, onSave }: { agent: Agent; onClose(): void; onSave(input: UpdateAgentInput): Promise<void> }) {
  const [form, setForm] = useState({ name: agent.name, role: agent.role, goal: agent.goal }); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await onSave(form); onClose(); } finally { setSaving(false); } }
  return <DialogShell title={`Edit ${agent.name}`} onClose={onClose}><form className="dialog-form" onSubmit={submit}><label>Name<input autoFocus required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Role<input required value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} /></label><label>Goal<textarea required value={form.goal} onChange={(event) => setForm({ ...form, goal: event.target.value })} /></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving…" : "Save agent"}</button></div></form></DialogShell>;
}
export function DeleteAgentDialog({ agent, onClose, onDelete }: { agent: Agent; onClose(): void; onDelete(): Promise<void> }) {
  const [deleting, setDeleting] = useState(false);
  async function remove() { setDeleting(true); try { await onDelete(); onClose(); } finally { setDeleting(false); } }
  return <DialogShell title={`Delete ${agent.name}?`} onClose={onClose}><div className="delete-agent-copy"><p>This removes the agent, its local mock conversation, approval state, and computer preview.</p><strong>This action cannot be undone.</strong></div><div className="dialog-actions delete-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button destructive-button" disabled={deleting} onClick={() => void remove()}>{deleting ? "Deleting…" : "Delete agent"}</button></div></DialogShell>;
}
export function SettingsDialog({ onClose }: { onClose(): void }) {
  const [settings, setSettings] = useState<AppSettings>({ endpoint: "", dashboardUrl: "", theme: "light", notifications: true }); const [token, setToken] = useState(""); const [hasToken, setHasToken] = useState(false); const [version, setVersion] = useState("Development"); const [saved, setSaved] = useState(false); const [authStatus, setAuthStatus] = useState("idle");
  useEffect(() => { void window.runtaCrew?.settings.get().then(setSettings); void window.runtaCrew?.credentials.has().then(setHasToken); void window.runtaCrew?.getVersion().then(setVersion); }, []);
  async function save(event: FormEvent) { event.preventDefault(); await window.runtaCrew?.settings.set(settings); if (token) { await window.runtaCrew?.credentials.set(token); setHasToken(true); setToken(""); } setSaved(true); document.documentElement.dataset.theme = settings.theme; window.setTimeout(() => setSaved(false), 1500); }
  async function authorize() { await window.runtaCrew?.settings.set(settings); const started = await window.runtaCrew?.auth?.start(); if (!started) return; setAuthStatus("pending"); const timer = window.setInterval(async () => { const next = await window.runtaCrew?.auth?.status(); if (!next) return; setAuthStatus(next); if (next !== "pending") { window.clearInterval(timer); if (next === "authorized") setHasToken(true); } }, 1000); }
  return <DialogShell title="Settings" onClose={onClose}><form className="settings-form" onSubmit={save}><section><h3>Connection</h3><label>API base URL<input type="url" placeholder="https://app.forge/api" value={settings.endpoint} onChange={(e) => setSettings({ ...settings, endpoint: e.target.value })} /></label><label>Dashboard URL<input type="url" placeholder="https://app.forge" value={settings.dashboardUrl} onChange={(e) => setSettings({ ...settings, dashboardUrl: e.target.value })} /></label><button type="button" onClick={() => void authorize()}>{hasToken ? "Reconnect Runta account" : "Sign in with Runta"}</button><small>{authStatus === "pending" ? "Complete authorization in your browser…" : authStatus === "authorized" ? "Runta account connected." : "Authorization opens in the Runta Dashboard. Credentials stay in operating-system encrypted storage."}</small><details><summary>Advanced: API token</summary><label>API token<input type="password" autoComplete="off" placeholder={hasToken ? "Token stored securely" : "Paste token"} value={token} onChange={(e) => setToken(e.target.value)} /></label></details></section><section><h3>Appearance</h3><label>Theme<select value={settings.theme} onChange={(e) => setSettings({ ...settings, theme: e.target.value as ThemePreference })}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label className="checkbox"><input type="checkbox" checked={settings.notifications} onChange={(e) => setSettings({ ...settings, notifications: e.target.checked })} /> Notifications for approvals and completed work</label></section><section className="about-row"><div><h3>Runta Crew</h3><p>Desktop client for Runta Cloud Agents</p></div><span>Version {version}</span></section><div className="dialog-actions"><span className="saved-label">{saved ? "Saved" : ""}</span><button className="primary-button">Save changes</button></div></form></DialogShell>;
}
