import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { Resvg } from "@resvg/resvg-js";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import Avatar from "boring-avatars";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const style = JSON.parse(readFileSync(join(root, "src/shared/avatarStyle.json"), "utf8"));
const avatar = renderToStaticMarkup(createElement(Avatar, {
  name: `${style.seedPrefix}${style.iconName.trim().toLocaleLowerCase()}`,
  colors: style.colors, variant: "beam", square: true, title: false, size: 1024,
}));
const artwork = avatar.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" fill="none">
  <title>Errand</title>
  <desc>Errand's curated beam avatar, generated with the same avatar library as the app's agents.</desc>
  <!-- Generated by scripts/build-icons.mjs using boring-avatars (MIT, boringdesigners). -->
  <defs><clipPath id="errand-tile"><rect x="64" y="64" width="896" height="896" rx="216"/></clipPath></defs>
  <g clip-path="url(#errand-tile)"><svg x="64" y="64" width="896" height="896" viewBox="0 0 36 36" fill="none">${artwork}</svg></g>
</svg>\n`;
writeFileSync(join(root, "src/assets/errand-icon.svg"), svg);
const render = (size) => new Resvg(svg, { fitTo: { mode: "width", value: size }, font: { loadSystemFonts: false } }).render().asPng();
mkdirSync(join(root, "build"), { recursive: true });
writeFileSync(join(root, "build/icon.png"), render(1024));

if (process.platform === "darwin") {
  const temporary = mkdtempSync(join(tmpdir(), "errand-icons-"));
  const iconset = join(temporary, "Errand.iconset");
  try {
    mkdirSync(iconset);
    for (const size of [16, 32, 128, 256, 512]) {
      writeFileSync(join(iconset, `icon_${size}x${size}.png`), render(size));
      writeFileSync(join(iconset, `icon_${size}x${size}@2x.png`), render(size * 2));
    }
    execFileSync("iconutil", ["-c", "icns", iconset, "-o", join(root, "build/icon.icns")]);
  } finally { rmSync(temporary, { recursive: true, force: true }); }
}
console.log("Generated Errand SVG, PNG, and macOS icons from the shared beam avatar style.");
